version: '3.9'

services:
  baza-front:
    env_file:
      - .env
    build: .
    container_name: baza-front
    restart: unless-stopped
    ports:
      - 3000:3002
    networks:
      - localnet

networks:
  localnet:
    external: true
    name: localnet
