export const projects = [
  {
    _id: '1',
    title: 'Murrfecto',
    imageUrl: '/img/projects/murrfecto.png',
    status: 'active',
    link: 'https://murrfecto.site',
    description: 'Сайт притулку для вуличних тварин Murrfecto',
    creationDate: 1682283600000,
    launchDate: 1686517200000,
    complexity: 2,
    teamMembers: [
      /*{
        user: {
          _id: '6471fa06933513f26024a99',
          name: 'some name',
          link: 'https://www.linkedin.com/feed/',
        },
        role: {
          _id: '6471f9a29c17ac2190eb879',
          name: 'PM',
        },
      },  */
    ],
  },
  {
    _id: '4',
    title: 'Ataka Help',
    imageUrl: '/img/projects/atack.png',
    status: 'active',
    link: 'https://ataka-help.tech',
    description: 'Платформа про види кібершахрайства AtakaHelp',
    creationDate: 1683493200000,
    launchDate: 1687726800000,
    complexity: 2,
    teamMembers: [],
  },
  {
    _id: '6',
    title: 'baza',
    imageUrl: '/img/projects/baza.png',
    status: 'active',
    link: 'https://baza-trainee.tech',
    description: 'Платформа для Baza Trainee Ukraine',
    creationDate: 1683234000000,
    launchDate: 1687467600000,
    complexity: 3,
    teamMembers: [],
  },
  {
    _id: '2',
    title: 'Читозаврик',
    imageUrl: '/img/projects/zavr.png',
    status: 'under-development',
    link: ' ',
    description: 'Читозаврик - веб-додаток з книжковими вікторинами для дітей',
    creationDate: 1685566800000,
    launchDate: 0,
    complexity: 5,
    teamMembers: [],
  },
  {
    _id: '5',
    title: '1001 songs',
    imageUrl: '/img/projects/1001songs.jpg',
    status: 'under-development',
    link: ' ',
    description: '1001 songs - сайт-колекція українських автентичних пісень ',
    creationDate: 1685566800000,
    launchDate: 0,
    complexity: 3,
    teamMembers: [],
  },
  {
    _id: '3',
    title: 'Big Lapa',
    imageUrl: '/img/projects/lapa.png',
    status: 'under-development',
    link: ' ',
    description: 'Сайт притулку для вуличних тварин Big Lapa',
    creationDate: 1685566800000,
    launchDate: 0,
    complexity: 2,
    teamMembers: [],
  },
  {
    _id: '7',
    title: 'feeda',
    imageUrl: '/img/projects/feeda-1.png',
    status: 'under-development',
    link: ' ',
    description:
      'Feeda - платформа для обробки заявок на участь у Baza Trainee',
    creationDate: 1687208400000,
    launchDate: 0,
    complexity: 2,
    teamMembers: [],
  },
  {
    _id: '8',
    title: 'book',
    imageUrl: '/img/projects/book.jpg',
    status: 'under-development',
    link: ' ',
    description: 'Книжка їде за кордон - портал гуманітарної допомоги',
    creationDate: 1688245200000,
    launchDate: 0,
    complexity: 2,
    teamMembers: [],
  },
  {
    _id: '9',
    title: 'arms',
    imageUrl: '/img/projects/arms.jpg',
    status: 'under-development',
    link: ' ',
    description: 'Лендинг - збір коштів для 59-бригади “Сталеві Обійми”',
    creationDate: 1689368400000,
    launchDate: 0,
    complexity: 2,
    teamMembers: [],
  },
];
